version: '3.8'

services:
  redis:
    image: 'redis:alpine'
    command: ['redis-server', '--requirepass', '${REDIS_PASSWORD}']
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis_data:/data
    env_file:
      - .env

volumes:
  redis_data:
